### ISSUE TITLE
关于 英特尔 N-6205 网卡 无法启动5g wifi

### ISSUE THREAD

**Issue by Vip4pt** [istoreos/istoreos#1035]
我用的无限网卡是英特尔®迅驰® Advanced-N 6205，找到了对应的包是：iwlwifi-firmware-iwl6000g2a，这网卡是支持5G的~
![K4O~)W2NB2L7ARYBZJGZDW4](https://github.com/istoreos/istoreos/assets/21324892/e0d652b1-e4d0-44b8-b380-590facadfdf7)
已经成功开启了无线选项，但5G不可用
![image](https://github.com/istoreos/istoreos/assets/21324892/cedb0ae8-90b1-4ef4-921c-4943032f07b4)
一旦设置5G信号就会禁用，只能使用2.4G了~

lspci可以获取到无线网卡信息：
![image](https://github.com/istoreos/istoreos/assets/21324892/ac6d17ad-d178-46dd-ae16-37cdd0f16421)

求解~

**Comment by jjm2473** [comment]
Intel 的所有无线网卡都只能作为客户端，不能作为AP，参考 https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi  ：

### Features
Station (client)
AP mode on 2.4GHz (on devices driven by iwlmvm, note no 5GHz AP support [due to LAR](https://bugzilla.kernel.org/show_bug.cgi?id=206469#c2))
P2P and multi-role (on devices driven by iwlmvm)
Monitor (sniffer) - see [note](https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi#about_the_monitorsniffer_mode)
IBSS (Ad-Hoc)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/2692/1
